### ISSUE TITLE
我发送Dashboard的邮件到qq邮箱，里面的中文会产生框框的乱码，怎么解决？？

### ISSUE THREAD

**Issue by lx87139511** [edp963/davinci-docker#10]
![微信图片111111](https://user-images.githubusercontent.com/57161477/70875187-0b467380-1ff0-11ea-8367-3ca0e37362ab.png)

**Comment by lx87139511** [comment]
直接url访问是正常的，只有发送邮件的时候才会产生中文乱码

**Comment by cabbage89** [comment]
163邮箱没有乱码，其它邮箱不确定

**Comment by michelle-q** [comment]
用容器部署的服务执行定时任务时会报错：
2020-03-22 15:47:20.649  INFO 16 --- [pool-7-thread-1] e.d.service.screenshot.ScreenshotUtil    : finish screenshot for job: 8
java.lang.IllegalArgumentException: File must not be null
        at org.springframework.util.Assert.notNull(Assert.java:193)
        at org.springframework.mail.javamail.MimeMessageHelper.addInline(MimeMessageHelper.java:912)
        at edp.core.utils.MailUtils.lambda$sendMail$1(MailUtils.java:188)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at edp.core.utils.MailUtils.sendMail(MailUtils.java:185)
        at edp.davinci.service.impl.EmailScheduleServiceImpl.execute(EmailScheduleServiceImpl.java:206)
        at edp.core.common.quartz.QuartzJobExecutor.lambda$execute$0(QuartzJobExecutor.java:64)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

有遇到相同问题么

**Comment by cabbage89** [comment]
我知道什么问题，在更新新的docker镜像后需要在 dockerfile里面添加 

ENV OPENSSL_CONF=/etc/ssl/
