### ISSUE TITLE
使用windows平台下的docker能部署但是在注册时一直报internal server error

### ISSUE THREAD

**Issue by THyyy** [edp963/davinci-docker#4]
报错信息如下：
davinci_1  | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
davinci_1  |    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
davinci_1  |    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
davinci_1  |    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
davinci_1  |    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
davinci_1  |    ... 84 more
davinci_1  | 2019-06-10 14:00:22.344 ERROR 25 --- [0.0-8080-exec-3] e.d.core.config.RestExceptionHandler     : Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
davinci_1  |   nested exception is:
davinci_1  |    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
davinci_1  |   nested exception is:
davinci_1  |    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
davinci_1  | 2019-06-10 14:00:22.344 ERROR 25 --- [http-nio-0.0.0.0-8080-exec-3] e.d.core.config.RestExceptionHandler     : Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
davinci_1  |   nested exception is:
davinci_1  |    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
davinci_1  |   nested exception is:
davinci_1  |    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
我猜测是因为 win10 的 SSL 密钥库路径不匹配的问题，但是无法确定。

**Comment by THyyy** [comment]
> 报错信息如下：
> davinci_1 | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> davinci_1 | at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
> davinci_1 | at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
> davinci_1 | at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> davinci_1 | at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
> davinci_1 | ... 84 more
> davinci_1 | 2019-06-10 14:00:22.344 ERROR 25 --- [0.0-8080-exec-3] e.d.core.config.RestExceptionHandler : Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
> davinci_1 | nested exception is:
> davinci_1 | javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
> davinci_1 | nested exception is:
> davinci_1 | javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> davinci_1 | 2019-06-10 14:00:22.344 ERROR 25 --- [http-nio-0.0.0.0-8080-exec-3] e.d.core.config.RestExceptionHandler : Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
> davinci_1 | nested exception is:
> davinci_1 | javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 465;
> davinci_1 | nested exception is:
> davinci_1 | javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 我猜测是因为 win10 的 SSL 密钥库路径不匹配的问题，但是无法确定。

关闭了SSL连接然后使用QQ邮箱的smtp.qq.com的25端口可以成功启动。
证实了我的猜测！

**Comment by chen769330532** [comment]
能说下大概怎么弄吗
